networks:
  dev:

services:

  postgres:
    image: postgres:15
    container_name: soglasie_db
    restart: always
    environment:
      POSTGRES_DB: soglasie
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dev

  backend:
    build:
      context: .
    container_name: soglasie_backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/soglasie
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
    depends_on:
      - postgres
    networks:
      - dev

volumes:
  postgres_data:
    driver: local